Added new command details
fortinet-fortisoar/solution-pack-fortisoar-for-microsoft-teams pull request #10
Opened 2023-09-05 11:57 UTC by cs-shivaji-kolape

Following changes added in this PR
1. Adds New `availableCommands` details
2. Updated help message screenshot. 
3. Updated `Create Alert` and Create Indictor Playbook Description.

2023-09-05 12:12 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +
This command brings up lists all available tags that can be used to trigger a playbook. --> This command brings up list of all available tags that can be used to trigger a playbook in FortiSOAR.

2023-09-05 12:13 UTC, cs-suyog-jinturkar commented on docs/res/help-message.png
Please review and change "Lists all available tag that...." to "List all available tags that...."

2023-09-05 13:35 UTC, cs-suyog-jinturkar approved these changes

2023-09-06 08:05 UTC, cs-abhishek-shukla requested changes

2023-09-06 08:05 UTC, cs-abhishek-shukla commented on docs/contents.md
> +| Create Indicator       | Extracts indicators from the text provided as input. Gets triggered on createIndicator command when used in Microsoft Teams                   |
Extracts indicators from the text sent on the chat interface and is triggered when `createIndicator` command is sent through Microsoft Teams.

2023-09-06 08:05 UTC, cs-abhishek-shukla commented on docs/contents.md
> +| Create Alert           | Creates an alert based on the values provided in the form. Gets triggered on createAlert command when used in Microsoft Teams                 |
Creates an alert based on the values provided in the form and is triggered when `createAlert` command is sent through Microsoft Teams.

2023-09-06 08:05 UTC, cs-abhishek-shukla commented on docs/usage.md
> +This command brings up list of all available tags that can be used to trigger a playbook in FortiSOAR.
This command brings up a list of all available tags that can be used to trigger a playbook in FortiSOAR&trade;.

2023-09-06 09:34 UTC, cs-abhishek-shukla approved these changes

2023-09-06 09:46 UTC, merged