1.0.0 doc changes
fortinet-fortisoar/solution-pack-fortisoar-for-microsoft-teams pull request #7
Opened 2023-07-20 13:25 UTC by cs-abhishek-shukla

- Fixed Typo, Grammar, label names, doc structure, and information flow issues
- Rewrote the usage section linking to the FortiSOAR documentation

2023-07-20 13:29 UTC, cs-suyog-jinturkar commented on README.md
> +- **Compatible Version**: FortiSOAR&trade; cloud instance
Fortisoar cloud instance or FortiSOAR cloud? Please check with other docs

2023-07-20 13:36 UTC, cs-suyog-jinturkar commented on docs/contents.md
> +| Create Alert                   | Creates an alert based on the values provided in the form                                                                      |
All three PBS are triggered from Ms teams as part of FSR command exec. We can have consistent description for them...

2023-07-20 13:44 UTC, cs-suyog-jinturkar commented on docs/contents.md
> +| Enrich IP From Microsoft Teams | Reference playbook that gets triggered from Microsoft Teams based and provides latest reputation formatted for Microsoft Teams |
This description should be changed to "Reference playbook that gets triggered and provides latest well formatted reputation using configured threat Intel platform"

2023-07-20 13:53 UTC, cs-suyog-jinturkar commented on docs/setup.md
> +- For optimal performance of **FortiSoar for Microsoft Teams** solution pack, you can install and configure the following connectors:
FortiSOAR

2023-07-20 13:55 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +This section gives a brief description on some of the commands used in FortiSOAR&trade; for Microsoft Teams application.
Some?? we mentioned all supported cmds

2023-07-20 13:57 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +2. Takes the name and description entered in the manual input form on the MS Teams app to create a new alert in FortiSOAR&trade;.
Please use consistent language like "Microsoft Teams application"

2023-07-20 13:58 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +1. Displays a **Create New Alert** form.
Form or adaptive card or form aka adaptive card?

2023-07-20 14:01 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +2. Takes the indicator value from the command to create an indicator in FortiSOAR&trade; with the information specified in the input form on the MS Teams app.
Same as above

2023-07-20 14:01 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +This command adds an indicator of value `gumblar.cn` in FortiSOAR&trade;
Add or create?

2023-07-20 14:03 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +This command adds an indicator of value `gumblar.cn` in FortiSOAR&trade;
Please use consistently

2023-07-20 14:04 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +This command takes another argument `<tag_name>` to trigger the playbook containing the tag `<tag_name>`.
FortiSOAR pb or pb in FortiSOAR

2023-07-20 14:05 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +> **NOTE**:  If there are multiple playbooks with the same tag, the first found playbook is executed.
Executed or triggered?? Consistently is missing

2023-07-20 14:05 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +To create playbooks that can be triggered from Microsoft Teams chat interface, refer to [Create a custom playbook to be triggered from Microsoft Teams](https://docs.fortinet.com/document/fortisoar/1.
Chat or App?

2023-07-20 14:06 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +The command invokes the playbooks with the tag `getIPRep`.
Invokes or triggers??

2023-07-20 14:07 UTC, cs-suyog-jinturkar commented on docs/usage.md
> +>**NOTE**: The playbook being invoked must have a `bot_enabled` tag.
The playbook being invoked must have a `bot_enabled` tag.  --> The playbook being invoked must ALSO have a `bot_enabled` tag.

2023-07-21 09:16 UTC, cs-abhinav-goel commented on docs/contents.md
> +| VirusTotal      | Scans and analyzes suspicious files, URLs, IP addresses and retrieves reports from VirusTotal about them
With this SP, no Virus Total & IPStack connector gets Installed.

2023-07-24 06:47 UTC, cs-abhinav-goel requested changes

2023-07-24 06:47 UTC, cs-abhinav-goel commented on docs/contents.md
> +| Microsoft Teams Link | Sends a message to Microsoft Teams when certain rule is met.  |
@cs-abhishek-shukla : Can we have some other wording. 
Like "Sends a message to Microsoft Teams having link to the Manual Input when a rule using this channel is triggered"

2023-07-24 06:47 UTC, cs-abhinav-goel commented on docs/contents.md
> +| Microsoft Teams      | Sends a inline interactive form to the Microsoft Teams application. |
@cs-abhishek-shukla : Similarly for this one. @shivaji can help you with this one.

2023-07-24 06:47 UTC, cs-abhinav-goel commented on docs/contents.md
>      ![](./res/inline-form.png)
Need to update the Image, as in the current Every line refer below image
![image](https://github.com/fortinet-fortisoar/solution-pack-fortisoar-for-microsoft-teams/assets/24773177/3886e7cb-ea2b-4f20-af9b-55a4f2443a30)

2023-07-24 06:47 UTC, cs-abhinav-goel commented on docs/contents.md
> +| Enrich IP From Microsoft Teams | A reference playbook triggered from Microsoft Teams chat interface and provides latest reputation information with formatting in-line with Teams interface |
@cs-abhishek-shukla : The Playbooks for "Enrich IP From Microsoft Teams" is incorrect.

We have below Playbook 
>"Enrich IP"  | Gets triggered on enrichIP command when used in Microsoft Teams
>"Enrich IP > Enrichment" | Reference playbook that gets triggered from Microsoft Teams based and provides latest reputation formatted for Microsoft Teams

@cs-abhishek-shukla

2023-08-01 05:15 UTC, cs-abhinav-goel approved these changes
Looks good from my side

2023-08-01 06:19 UTC, cs-suyog-jinturkar approved these changes

2023-08-01 06:19 UTC, merged